using System;
using System.Collections.Generic;

namespace APIProfit2K8.Models
{
    public partial class Ambart
    {
        public string AmbUsua { get; set; }
        public bool? CoArtv { get; set; }
        public bool? ArtDesv { get; set; }
        public bool? FechaRegv { get; set; }
        public bool? ManjServ { get; set; }
        public bool CoLind { get; set; }
        public bool? CoLinv { get; set; }
        public string CoLin { get; set; }
        public bool CoCatd { get; set; }
        public bool? CoCatv { get; set; }
        public string CoCat { get; set; }
        public bool CoSubld { get; set; }
        public bool? CoSublv { get; set; }
        public string CoSubl { get; set; }
        public bool CoColord { get; set; }
        public bool? CoColorv { get; set; }
        public string CoColor { get; set; }
        public bool? Itemv { get; set; }
        public bool? Refv { get; set; }
        public bool? Modelov { get; set; }
        public bool Procedencd { get; set; }
        public bool? Procedencv { get; set; }
        public string Procedenci { get; set; }
        public bool? Comentariv { get; set; }
        public bool CoProvd { get; set; }
        public bool? CoProvv { get; set; }
        public string CoProv { get; set; }
        public bool? Ubicacionv { get; set; }
        public bool RelacAutd { get; set; }
        public bool? RelacAutv { get; set; }
        public int RelacAut { get; set; }
        public bool? PtoPedidv { get; set; }
        public bool? BtAranc { get; set; }
        public bool? StockMaxv { get; set; }
        public bool? StockMinv { get; set; }
        public bool? PrecOmv { get; set; }
        public bool? PrecVta1v { get; set; }
        public bool? PrecVta2v { get; set; }
        public bool? PrecVta3v { get; set; }
        public bool? PrecVta4v { get; set; }
        public bool? PrecVta5v { get; set; }
        public bool? PrecAgr1v { get; set; }
        public bool? PrecAgr2v { get; set; }
        public bool? PrecAgr3v { get; set; }
        public bool? PrecAgr4v { get; set; }
        public bool? PrecAgr5v { get; set; }
        public bool? CanAgrv { get; set; }
        public bool? MargMinv { get; set; }
        public bool? UltCosV { get; set; }
        public bool? CosProV { get; set; }
        public bool? CosMercV { get; set; }
        public bool? CosProvV { get; set; }
        public bool? UltCosdov { get; set; }
        public bool? CosUnanv { get; set; }
        public bool? UltCosomv { get; set; }
        public bool? CosProomv { get; set; }
        public bool? FecProomv { get; set; }
        public bool TipoCosd { get; set; }
        public bool? TipoCosv { get; set; }
        public string TipoCos { get; set; }
        public bool? MontComiv { get; set; }
        public bool? PuntCliv { get; set; }
        public bool? PuntProv { get; set; }
        public bool? Anuladov { get; set; }
        public bool TipoImpd { get; set; }
        public bool? TipoImpv { get; set; }
        public string TipoImp { get; set; }
        public bool? Licorv { get; set; }
        public bool? Picturev { get; set; }
        public string Campo1 { get; set; }
        public string Campo2 { get; set; }
        public string Campo3 { get; set; }
        public string Campo4 { get; set; }
        public string Campo5 { get; set; }
        public string Campo6 { get; set; }
        public string Campo7 { get; set; }
        public string Campo8 { get; set; }
        public string CoUsIn { get; set; }
        public DateTime FeUsIn { get; set; }
        public string CoUsMo { get; set; }
        public DateTime FeUsMo { get; set; }
        public string CoUsEl { get; set; }
        public DateTime FeUsEl { get; set; }
        public string Revisado { get; set; }
        public string Trasnfe { get; set; }
        public string CoSucu { get; set; }
        public bool? Pesov { get; set; }
        public bool? Piev { get; set; }
        public bool? Margen1v { get; set; }
        public bool? Margen2v { get; set; }
        public bool? Margen3v { get; set; }
        public bool? Margen4v { get; set; }
        public bool? Margen5v { get; set; }
        public bool Tipod { get; set; }
        public bool? Tipov { get; set; }
        public string Tipo { get; set; }
        public bool? Lotev { get; set; }
        public bool? Reactivar { get; set; }
        public bool? Relacartv { get; set; }
        public bool? PorcAdiv { get; set; }
        public bool? Garantiav { get; set; }
        public Guid Rowguid { get; set; }
        public bool? BtPreclote { get; set; }
        public bool? ArtDesiv { get; set; }
        public bool? Imagen1v { get; set; }
        public bool? Imagen2v { get; set; }
        public string Primaria { get; set; }
        public string Secundaria { get; set; }
        public string Alterna { get; set; }
        public decimal EquiPri { get; set; }
        public decimal EquiSec { get; set; }
        public decimal EquiAlt { get; set; }
        public decimal UniRelac1 { get; set; }
    }
}
