using System;
using System.Collections.Generic;

namespace APIProfit2K8.Models
{
    public partial class Ambclpro
    {
        public string AmbUsua { get; set; }
        public string TipoCyp { get; set; }
        public bool? CoCliv { get; set; }
        public bool Tipod { get; set; }
        public bool? Tipov { get; set; }
        public string Tipo { get; set; }
        public bool? CliDesv { get; set; }
        public bool? Direc1v { get; set; }
        public bool? Direc2v { get; set; }
        public bool? Telefonosv { get; set; }
        public bool Faxv { get; set; }
        public bool? Inactivov { get; set; }
        public bool? Comentariv { get; set; }
        public bool? Responsv { get; set; }
        public bool? FechaRegv { get; set; }
        public bool? Saldov { get; set; }
        public bool? MontCrev { get; set; }
        public bool? PlazPagv { get; set; }
        public bool? Descppagov { get; set; }
        public bool ConZond { get; set; }
        public bool? CoZonv { get; set; }
        public string CoZon { get; set; }
        public bool CoSegd { get; set; }
        public bool? CoSegv { get; set; }
        public string CoSeg { get; set; }
        public bool ConVend { get; set; }
        public bool? CoVenv { get; set; }
        public string CoVen { get; set; }
        public bool? DescGlobv { get; set; }
        public bool? Horarcajav { get; set; }
        public bool? Frecuvistv { get; set; }
        public bool? Lunesv { get; set; }
        public bool? Martesv { get; set; }
        public bool? Miercolesv { get; set; }
        public bool? Juevesv { get; set; }
        public bool? Viernesv { get; set; }
        public bool? Sabadov { get; set; }
        public bool? Domingov { get; set; }
        public bool? DirEnt2v { get; set; }
        public bool? Rifv { get; set; }
        public bool? Contribuv { get; set; }
        public bool? DisCenv { get; set; }
        public bool? Nitv { get; set; }
        public bool? Emailv { get; set; }
        public bool CoIngrd { get; set; }
        public bool? CoIngrv { get; set; }
        public string CoIngr { get; set; }
        public bool TipoPerd { get; set; }
        public bool? TipoPerv { get; set; }
        public string TipoPer { get; set; }
        public bool? CoTabv { get; set; }
        public bool TipoAdid { get; set; }
        public bool? TipoAdiv { get; set; }
        public int TipoAdi { get; set; }
        public bool Matrizd { get; set; }
        public bool? Matrizv { get; set; }
        public string Matriz { get; set; }
        public string Campo1 { get; set; }
        public string Campo2 { get; set; }
        public string Campo3 { get; set; }
        public string Campo4 { get; set; }
        public string Campo5 { get; set; }
        public string Campo6 { get; set; }
        public string Campo7 { get; set; }
        public string Campo8 { get; set; }
        public string CoUsIn { get; set; }
        public DateTime FeUsIn { get; set; }
        public string CoUsMo { get; set; }
        public DateTime FeUsMo { get; set; }
        public string CoUsEl { get; set; }
        public DateTime FeUsEl { get; set; }
        public string Revisado { get; set; }
        public string Trasnfe { get; set; }
        public string CoSucu { get; set; }
        public string Serialp { get; set; }
        public bool Valido { get; set; }
        public Guid Rowguid { get; set; }
        public bool? Loginv { get; set; }
        public bool? Passwordv { get; set; }
        public bool? Estadov { get; set; }
        public bool Vpasswordv { get; set; }
        public bool? CoPaisv { get; set; }
        public bool? CoPaisd { get; set; }
        public string CoPais { get; set; }
        public bool? Zipv { get; set; }
        public bool? Ciudadv { get; set; }
        public bool? TaxIdv { get; set; }
        public bool? FormTypev { get; set; }
        public bool FormTyped { get; set; }
        public string FormType { get; set; }
        public bool? WebSitev { get; set; }
        public bool? BwebSitev { get; set; }
        public bool? Bemailv { get; set; }
        public bool? Salestaxv { get; set; }
        public bool Salestaxd { get; set; }
        public string Salestax { get; set; }
    }
}
