using System;
using System.Collections.Generic;

namespace APIProfit2K8.Models
{
    public partial class Amblfact
    {
        public string AmbUsua { get; set; }
        public string AmbBlfa { get; set; }
        public bool? FactNum { get; set; }
        public bool? Contrib { get; set; }
        public bool? Descrip { get; set; }
        public bool? FecEmis { get; set; }
        public bool? FecVenc { get; set; }
        public string VcoCli { get; set; }
        public bool DcoCli { get; set; }
        public bool? CoCli { get; set; }
        public string VcoVen { get; set; }
        public bool DcoVen { get; set; }
        public bool? CoVen { get; set; }
        public string VcoTran { get; set; }
        public bool DcoTran { get; set; }
        public bool? CoTran { get; set; }
        public string VformaPag { get; set; }
        public bool DformaPag { get; set; }
        public bool? FormaPag { get; set; }
        public string Vmoneda { get; set; }
        public bool Dmoneda { get; set; }
        public bool? Moneda { get; set; }
        public bool MontoAdi { get; set; }
        public bool? ComRelac { get; set; }
        public bool? PorcGdesc { get; set; }
        public bool? PorcReca { get; set; }
        public bool? TotFlete { get; set; }
        public bool? StockNeg { get; set; }
        public bool CobrarAut { get; set; }
        public int NumListar { get; set; }
        public int Listar { get; set; }
        public bool PstockNeg { get; set; }
        public bool? Pc1 { get; set; }
        public bool? Pc2 { get; set; }
        public bool? Pc3 { get; set; }
        public bool? Pc4 { get; set; }
        public bool? Pc5 { get; set; }
        public bool Saldo { get; set; }
        public bool? Fvenc { get; set; }
        public bool? Chdev { get; set; }
        public int Numcopia { get; set; }
        public decimal Vreng4 { get; set; }
        public bool Dreng4 { get; set; }
        public string Vsucursal { get; set; }
        public string Vreng3 { get; set; }
        public bool Dreng3 { get; set; }
        public bool? Reng3 { get; set; }
        public bool? Reng4 { get; set; }
        public bool? Reng5 { get; set; }
        public bool? Reng6 { get; set; }
        public bool? Reng7 { get; set; }
        public bool? Reng8 { get; set; }
        public bool? Reng9 { get; set; }
        public bool? Reng10 { get; set; }
        public bool? BCobrar { get; set; }
        public bool? BImportar { get; set; }
        public bool? BAnular { get; set; }
        public bool? BSeriales { get; set; }
        public bool? BNotas { get; set; }
        public bool? BMargen { get; set; }
        public int PMargen { get; set; }
        public bool? BClien { get; set; }
        public bool? BFact { get; set; }
        public int Tamcol01 { get; set; }
        public int Tamcol02 { get; set; }
        public int Tamcol03 { get; set; }
        public int Tamcol04 { get; set; }
        public int Tamcol05 { get; set; }
        public int Tamcol06 { get; set; }
        public int Tamcol07 { get; set; }
        public int Tamcol08 { get; set; }
        public int Tamcol09 { get; set; }
        public int Tamcol10 { get; set; }
        public int Tamcol11 { get; set; }
        public int Tamcol12 { get; set; }
        public int Tamcol13 { get; set; }
        public int Tamcol14 { get; set; }
        public int Tamcol15 { get; set; }
        public int Tamcol16 { get; set; }
        public int Tamcol17 { get; set; }
        public int Tamcol18 { get; set; }
        public int Tamcol19 { get; set; }
        public int Tamcol20 { get; set; }
        public int Poscol01 { get; set; }
        public int Poscol02 { get; set; }
        public int Poscol03 { get; set; }
        public int Poscol04 { get; set; }
        public int Poscol05 { get; set; }
        public int Poscol06 { get; set; }
        public int Poscol07 { get; set; }
        public int Poscol08 { get; set; }
        public int Poscol09 { get; set; }
        public int Poscol10 { get; set; }
        public int Poscol11 { get; set; }
        public int Poscol12 { get; set; }
        public int Poscol13 { get; set; }
        public int Poscol14 { get; set; }
        public int Poscol15 { get; set; }
        public int Poscol16 { get; set; }
        public int Poscol17 { get; set; }
        public int Poscol18 { get; set; }
        public int Poscol19 { get; set; }
        public int Poscol20 { get; set; }
        public string Campo1 { get; set; }
        public string Campo2 { get; set; }
        public string Campo3 { get; set; }
        public string Campo4 { get; set; }
        public string Campo5 { get; set; }
        public string Campo6 { get; set; }
        public string Campo7 { get; set; }
        public string Campo8 { get; set; }
        public string CoUsIn { get; set; }
        public DateTime FeUsIn { get; set; }
        public string CoUsMo { get; set; }
        public DateTime FeUsMo { get; set; }
        public string CoUsEl { get; set; }
        public DateTime FeUsEl { get; set; }
        public string Revisado { get; set; }
        public string Trasnfe { get; set; }
        public bool PPara1 { get; set; }
        public bool PPara2 { get; set; }
        public bool PPara3 { get; set; }
        public bool PPara4 { get; set; }
        public bool PPara5 { get; set; }
        public bool PPara6 { get; set; }
        public bool PPara7 { get; set; }
        public bool PPara8 { get; set; }
        public bool? PPara9 { get; set; }
        public bool? PPara10 { get; set; }
        public string CoSucu { get; set; }
        public Guid Rowguid { get; set; }
        public bool BReactivar { get; set; }
        public bool PDevReng { get; set; }
        public bool BArt { get; set; }
        public bool? BDevdinero { get; set; }
        public bool? BRevdinero { get; set; }
        public bool PLotefec { get; set; }
        public bool Pcontrol1 { get; set; }
        public bool Pcontrol2 { get; set; }
        public bool Pcontrol3 { get; set; }
        public bool Pcontrol4 { get; set; }
        public bool Pcontrol5 { get; set; }
        public int Serie { get; set; }
        public bool Pcontrol6 { get; set; }
        public bool Pcontrol7 { get; set; }
        public bool Pcontrol8 { get; set; }
        public bool Pcontrol9 { get; set; }
        public bool? Tax { get; set; }
        public string Vtax { get; set; }
        public bool Dtax { get; set; }
        public bool Numcontrol { get; set; }
        public bool Actforma { get; set; }
        public string Formapag1 { get; set; }
        public bool ManImpr { get; set; }
        public bool SerialLleno { get; set; }
        public bool DescFac { get; set; }
        public bool ReinArt { get; set; }
        public decimal Maxefec { get; set; }
        public bool Pimpfac { get; set; }
    }
}
