using System;
using System.Collections.Generic;

namespace APIProfit2K8.Models
{
    public partial class ParEmp
    {
        public string CodEmp { get; set; }
        public string EmpImp { get; set; }
        public int TempNum { get; set; }
        public int CfxgNum { get; set; }
        public int CcxgNum { get; set; }
        public int FactNum { get; set; }
        public int GiroNum { get; set; }
        public int Girocppnum { get; set; }
        public int NotaNum { get; set; }
        public int PedNum { get; set; }
        public int OrdNum { get; set; }
        public int CotcNum { get; set; }
        public int CotpNum { get; set; }
        public int NdeNum { get; set; }
        public int CbNum { get; set; }
        public int PgNum { get; set; }
        public int NdNum { get; set; }
        public int NdcppNum { get; set; }
        public int NcNum { get; set; }
        public int NccppNum { get; set; }
        public int ChdvNum { get; set; }
        public int Chdvcppnum { get; set; }
        public int CompNum { get; set; }
        public int DevpNum { get; set; }
        public int DevcNum { get; set; }
        public int AjusNum { get; set; }
        public int DepcNum { get; set; }
        public int TrasNum { get; set; }
        public int GenkNum { get; set; }
        public int OrdsNum { get; set; }
        public int OrdpNum { get; set; }
        public int EjepNum { get; set; }
        public int InteNum { get; set; }
        public decimal PorcDb { get; set; }
        public int PostNum { get; set; }
        public int Postcppnum { get; set; }
        public int RetenNum { get; set; }
        public int Retencppnum { get; set; }
        public int NdrNum { get; set; }
        public int NddNum { get; set; }
        public int MovcNum { get; set; }
        public int MovbNum { get; set; }
        public int DescNum { get; set; }
        public int Desccppnum { get; set; }
        public int NumKit { get; set; }
        public int FisiNum { get; set; }
        public int Docum1 { get; set; }
        public int Docum2 { get; set; }
        public string TempChar1 { get; set; }
        public string TempChar2 { get; set; }
        public string TempChar3 { get; set; }
        public string TempChar4 { get; set; }
        public string TempChar5 { get; set; }
        public string TempChar6 { get; set; }
        public string TempChar7 { get; set; }
        public string TempChar8 { get; set; }
        public bool PComvVol { get; set; }
        public bool PComvKlu { get; set; }
        public bool PComvVen { get; set; }
        public bool PComvCon { get; set; }
        public bool PComvRC { get; set; }
        public bool PComvRP { get; set; }
        public bool PComvTip { get; set; }
        public bool PDescArt { get; set; }
        public bool PDescCat { get; set; }
        public bool PDescGlo { get; set; }
        public bool PDescOfe { get; set; }
        public bool PDescLin { get; set; }
        public bool PPrecIsv { get; set; }
        public bool PPrec1Isv { get; set; }
        public bool PPrec2Isv { get; set; }
        public bool PPrec3Isv { get; set; }
        public bool PPrec4Isv { get; set; }
        public bool PPrec5Isv { get; set; }
        public bool PRoundfac { get; set; }
        public bool PRoundinf { get; set; }
        public int PValRed { get; set; }
        public bool PRoundequ { get; set; }
        public bool PRoundsup { get; set; }
        public bool PCostoDo { get; set; }
        public bool PComAuto { get; set; }
        public bool PStockNeg { get; set; }
        public bool PEntNew { get; set; }
        public bool PAjuComi { get; set; }
        public bool PDobleUn { get; set; }
        public bool PProntPg { get; set; }
        public bool PGrabRen { get; set; }
        public bool PPara1 { get; set; }
        public bool PPara2 { get; set; }
        public bool PPara3 { get; set; }
        public bool PPara4 { get; set; }
        public bool PPara5 { get; set; }
        public bool PPara6 { get; set; }
        public bool PPara7 { get; set; }
        public bool PPara8 { get; set; }
        public bool PPara9 { get; set; }
        public bool PPara10 { get; set; }
        public bool POpenCom { get; set; }
        public bool PMargCap { get; set; }
        public bool PDirEnt { get; set; }
        public bool PArt20 { get; set; }
        public bool PImpKit { get; set; }
        public bool PRedCom { get; set; }
        public bool PCyfDol { get; set; }
        public bool PSerArt { get; set; }
        public bool PArtDol { get; set; }
        public string MoneArt { get; set; }
        public bool PDebBan { get; set; }
        public bool PDebAut { get; set; }
        public bool PFactAlm { get; set; }
        public bool PDespacho { get; set; }
        public bool PIdb { get; set; }
        public decimal ValIdb { get; set; }
        public int Tempor1 { get; set; }
        public DateTime FechaRes { get; set; }
        public DateTime FechaFisi { get; set; }
        public bool OpenFisi { get; set; }
        public string Serial { get; set; }
        public string Cadena { get; set; }
        public string InvEmp { get; set; }
        public string TempChar { get; set; }
        public DateTime FecInte { get; set; }
        public DateTime TempFech { get; set; }
        public bool EleLinea { get; set; }
        public int LonLinea { get; set; }
        public bool EleCateg { get; set; }
        public int LonCateg { get; set; }
        public bool EleMedid { get; set; }
        public int LonMedid { get; set; }
        public bool EleItem { get; set; }
        public int LonItem { get; set; }
        public bool EleColor { get; set; }
        public int LonColor { get; set; }
        public bool EleCarter { get; set; }
        public string Caracter { get; set; }
        public int DecPrec { get; set; }
        public int DecCost { get; set; }
        public int CantArt { get; set; }
        public int TotalCod { get; set; }
        public bool TipoCom { get; set; }
        public bool? TipoLib { get; set; }
        public string CoUsIn { get; set; }
        public DateTime FeUsIn { get; set; }
        public string CoUsMo { get; set; }
        public DateTime FeUsMo { get; set; }
        public byte[] Logo { get; set; }
        public string Revisado { get; set; }
        public string Trasnfe { get; set; }
        public bool PSucursal { get; set; }
        public bool PImp65 { get; set; }
        public Guid Rowguid { get; set; }
        public bool PLicores { get; set; }
        public bool PLotenro { get; set; }
        public bool PLotefec { get; set; }
        public string Serverolap { get; set; }
        public string Dataolap { get; set; }
        public bool PLoteaut { get; set; }
        public decimal TipoInve { get; set; }
        public int AjuPosm { get; set; }
        public int AjuPosa { get; set; }
        public int AjuNegm { get; set; }
        public int AjuNega { get; set; }
        public int AjuPosmc { get; set; }
        public int AjuPosac { get; set; }
        public int AjuNegmc { get; set; }
        public int AjuNegac { get; set; }
        public int PlvNum { get; set; }
        public int PlcNum { get; set; }
        public int Pventa { get; set; }
        public int Turnosic { get; set; }
        public int Tabislr { get; set; }
        public string Moneda { get; set; }
        public int ImpNum { get; set; }
        public int RmaCli { get; set; }
        public int RmaProv { get; set; }
        public int RmaEntc { get; set; }
        public int RmaEntp { get; set; }
        public int RmaRegs { get; set; }
        public bool PProvNew { get; set; }
        public bool PSerNew { get; set; }
        public string Rmacliente { get; set; }
        public string RmaTrans { get; set; }
        public string Garantia { get; set; }
        public string ReemProv { get; set; }
        public string DesSer { get; set; }
        public decimal SerAuto { get; set; }
        public bool Pcontrol1 { get; set; }
        public bool Pcontrol2 { get; set; }
        public bool Pcontrol3 { get; set; }
        public bool Pcontrol4 { get; set; }
        public bool Pcontrol5 { get; set; }
        public string Idioma { get; set; }
        public bool Serie { get; set; }
        public decimal Aux01 { get; set; }
        public string Aux02 { get; set; }
        public bool Eprofit { get; set; }
        public string Pais { get; set; }
        public int EmpNum { get; set; }
        public int DmcNum { get; set; }
        public int TaxNum { get; set; }
        public int CedNum { get; set; }
        public int EntNum { get; set; }
        public bool Artinmp { get; set; }
        public int TipCosto { get; set; }
        public int TipCmat { get; set; }
        public string CoAent { get; set; }
        public int CieNum { get; set; }
        public int OdpNum { get; set; }
        public int ReqNum { get; set; }
        public int DevNum { get; set; }
        public string CoAsal { get; set; }
        public bool Devmax { get; set; }
        public int ExpNum { get; set; }
        public int InpNum { get; set; }
        public int CostNum { get; set; }
        public int ParNum { get; set; }
        public int EscNum { get; set; }
        public bool CierreMes { get; set; }
        public int PlaNum { get; set; }
        public int MenNum { get; set; }
        public int MaxLin { get; set; }
        public bool ValMax { get; set; }
        public string Server { get; set; }
        public string Namedb { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool ManImpr { get; set; }
        public bool Ptovta { get; set; }
        public int Tipcosdev { get; set; }
        public int DistNum { get; set; }
        public int ExpNumi { get; set; }
        public bool Manivalic { get; set; }
    }
}
