using System;
using System.Collections.Generic;

namespace APIProfit2K8.Models
{
    public partial class RmaAmb
    {
        public string AmbUsua { get; set; }
        public string AmbRma { get; set; }
        public bool RmaNum { get; set; }
        public bool NroEntPr { get; set; }
        public bool FecEmis { get; set; }
        public string VcoCli { get; set; }
        public bool DcoCli { get; set; }
        public bool CoCli { get; set; }
        public bool RmaProv { get; set; }
        public string VcoTran { get; set; }
        public bool DcoTran { get; set; }
        public bool CoTran { get; set; }
        public bool Descrip { get; set; }
        public string Vmoneda { get; set; }
        public bool Dmoneda { get; set; }
        public bool Moneda { get; set; }
        public string Vreng1 { get; set; }
        public bool Dreng1 { get; set; }
        public bool Reng1 { get; set; }
        public string Vreng2 { get; set; }
        public bool Dreng2 { get; set; }
        public bool Reng2 { get; set; }
        public string Vreng3 { get; set; }
        public bool Dreng3 { get; set; }
        public bool Reng3 { get; set; }
        public bool BArt { get; set; }
        public bool BImportar { get; set; }
        public bool BSeriales { get; set; }
        public bool BAnular { get; set; }
        public bool BProcesar { get; set; }
        public bool BReversar { get; set; }
        public bool BClien { get; set; }
        public int Tamcol01 { get; set; }
        public int Tamcol02 { get; set; }
        public int Tamcol03 { get; set; }
        public int Tamcol04 { get; set; }
        public int Tamcol05 { get; set; }
        public int Tamcol06 { get; set; }
        public int Tamcol07 { get; set; }
        public int Tamcol08 { get; set; }
        public int Tamcol09 { get; set; }
        public int Tamcol10 { get; set; }
        public int Tamcol11 { get; set; }
        public int Tamcol12 { get; set; }
        public int Tamcol13 { get; set; }
        public int Tamcol14 { get; set; }
        public int Tamcol15 { get; set; }
        public int Tamcol16 { get; set; }
        public int Tamcol17 { get; set; }
        public int Tamcol18 { get; set; }
        public int Tamcol19 { get; set; }
        public int Tamcol20 { get; set; }
        public int Tamcol21 { get; set; }
        public int Tamcol22 { get; set; }
        public int Poscol01 { get; set; }
        public int Poscol02 { get; set; }
        public int Poscol03 { get; set; }
        public int Poscol04 { get; set; }
        public int Poscol05 { get; set; }
        public int Poscol06 { get; set; }
        public int Poscol07 { get; set; }
        public int Poscol08 { get; set; }
        public int Poscol09 { get; set; }
        public int Poscol10 { get; set; }
        public int Poscol11 { get; set; }
        public int Poscol12 { get; set; }
        public int Poscol13 { get; set; }
        public int Poscol14 { get; set; }
        public int Poscol15 { get; set; }
        public int Poscol16 { get; set; }
        public int Poscol17 { get; set; }
        public int Poscol18 { get; set; }
        public int Poscol19 { get; set; }
        public int Poscol20 { get; set; }
        public int Poscol21 { get; set; }
        public int Poscol22 { get; set; }
        public bool Pseriales { get; set; }
        public bool PnvoProv { get; set; }
        public bool CambDoc { get; set; }
        public bool SinDocu { get; set; }
        public bool GarVenc { get; set; }
        public bool SerNulo { get; set; }
        public bool Saldo { get; set; }
        public bool Fvenc { get; set; }
        public bool Chdev { get; set; }
        public bool CambArt { get; set; }
        public bool EntcArt { get; set; }
        public int Listar { get; set; }
        public int NumListar { get; set; }
        public int Numcopia { get; set; }
        public string Campo1 { get; set; }
        public string Campo2 { get; set; }
        public string Campo3 { get; set; }
        public string Campo4 { get; set; }
        public string Campo5 { get; set; }
        public string Campo6 { get; set; }
        public string Campo7 { get; set; }
        public string Campo8 { get; set; }
        public string CoUsIn { get; set; }
        public DateTime FeUsIn { get; set; }
        public string CoUsMo { get; set; }
        public DateTime FeUsMo { get; set; }
        public string CoUsEl { get; set; }
        public DateTime FeUsEl { get; set; }
        public string Revisado { get; set; }
        public string Trasnfe { get; set; }
        public string CoSucu { get; set; }
        public Guid Rowguid { get; set; }
    }
}
